// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/petals.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Tensor represents activations or hidden states
type Tensor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                       // Unique tensor ID
	TaskId        string                 `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"` // The task ID this execution belongs to
	Data          []float64              `protobuf:"fixed64,3,rep,packed,name=data,proto3" json:"data,omitempty"`          // Matrix of float64 data
	Shape         []int64                `protobuf:"varint,4,rep,packed,name=shape,proto3" json:"shape,omitempty"`         // Dimensions of the tensor (e.g. [seq_len, hidden_dim])
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tensor) Reset() {
	*x = Tensor{}
	mi := &file_proto_petals_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tensor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tensor) ProtoMessage() {}

func (x *Tensor) ProtoReflect() protoreflect.Message {
	mi := &file_proto_petals_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tensor.ProtoReflect.Descriptor instead.
func (*Tensor) Descriptor() ([]byte, []int) {
	return file_proto_petals_proto_rawDescGZIP(), []int{0}
}

func (x *Tensor) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Tensor) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *Tensor) GetData() []float64 {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Tensor) GetShape() []int64 {
	if x != nil {
		return x.Shape
	}
	return nil
}

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	StartLayer    int32                  `protobuf:"varint,2,opt,name=start_layer,json=startLayer,proto3" json:"start_layer,omitempty"`
	EndLayer      int32                  `protobuf:"varint,3,opt,name=end_layer,json=endLayer,proto3" json:"end_layer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_proto_petals_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_petals_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_proto_petals_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *RegisterRequest) GetStartLayer() int32 {
	if x != nil {
		return x.StartLayer
	}
	return 0
}

func (x *RegisterRequest) GetEndLayer() int32 {
	if x != nil {
		return x.EndLayer
	}
	return 0
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_proto_petals_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_petals_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_proto_petals_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type RouteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartLayer    int32                  `protobuf:"varint,1,opt,name=start_layer,json=startLayer,proto3" json:"start_layer,omitempty"`
	EndLayer      int32                  `protobuf:"varint,2,opt,name=end_layer,json=endLayer,proto3" json:"end_layer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouteRequest) Reset() {
	*x = RouteRequest{}
	mi := &file_proto_petals_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteRequest) ProtoMessage() {}

func (x *RouteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_petals_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteRequest.ProtoReflect.Descriptor instead.
func (*RouteRequest) Descriptor() ([]byte, []int) {
	return file_proto_petals_proto_rawDescGZIP(), []int{3}
}

func (x *RouteRequest) GetStartLayer() int32 {
	if x != nil {
		return x.StartLayer
	}
	return 0
}

func (x *RouteRequest) GetEndLayer() int32 {
	if x != nil {
		return x.EndLayer
	}
	return 0
}

type RouteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Addresses     []string               `protobuf:"bytes,1,rep,name=addresses,proto3" json:"addresses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouteResponse) Reset() {
	*x = RouteResponse{}
	mi := &file_proto_petals_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteResponse) ProtoMessage() {}

func (x *RouteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_petals_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteResponse.ProtoReflect.Descriptor instead.
func (*RouteResponse) Descriptor() ([]byte, []int) {
	return file_proto_petals_proto_rawDescGZIP(), []int{4}
}

func (x *RouteResponse) GetAddresses() []string {
	if x != nil {
		return x.Addresses
	}
	return nil
}

type ForwardRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Tensor            *Tensor                `protobuf:"bytes,1,opt,name=tensor,proto3" json:"tensor,omitempty"`
	Route             []string               `protobuf:"bytes,2,rep,name=route,proto3" json:"route,omitempty"`                                                     // Fully planned route of node addresses
	CurrentRouteIndex int32                  `protobuf:"varint,3,opt,name=current_route_index,json=currentRouteIndex,proto3" json:"current_route_index,omitempty"` // Index of current node in the route path
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ForwardRequest) Reset() {
	*x = ForwardRequest{}
	mi := &file_proto_petals_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForwardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForwardRequest) ProtoMessage() {}

func (x *ForwardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_petals_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForwardRequest.ProtoReflect.Descriptor instead.
func (*ForwardRequest) Descriptor() ([]byte, []int) {
	return file_proto_petals_proto_rawDescGZIP(), []int{5}
}

func (x *ForwardRequest) GetTensor() *Tensor {
	if x != nil {
		return x.Tensor
	}
	return nil
}

func (x *ForwardRequest) GetRoute() []string {
	if x != nil {
		return x.Route
	}
	return nil
}

func (x *ForwardRequest) GetCurrentRouteIndex() int32 {
	if x != nil {
		return x.CurrentRouteIndex
	}
	return 0
}

type ForwardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tensor        *Tensor                `protobuf:"bytes,1,opt,name=tensor,proto3" json:"tensor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForwardResponse) Reset() {
	*x = ForwardResponse{}
	mi := &file_proto_petals_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForwardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForwardResponse) ProtoMessage() {}

func (x *ForwardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_petals_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForwardResponse.ProtoReflect.Descriptor instead.
func (*ForwardResponse) Descriptor() ([]byte, []int) {
	return file_proto_petals_proto_rawDescGZIP(), []int{6}
}

func (x *ForwardResponse) GetTensor() *Tensor {
	if x != nil {
		return x.Tensor
	}
	return nil
}

var File_proto_petals_proto protoreflect.FileDescriptor

const file_proto_petals_proto_rawDesc = "" +
	"\n" +
	"\x12proto/petals.proto\x12\x06petals\"[\n" +
	"\x06Tensor\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\tR\x06taskId\x12\x12\n" +
	"\x04data\x18\x03 \x03(\x01R\x04data\x12\x14\n" +
	"\x05shape\x18\x04 \x03(\x03R\x05shape\"i\n" +
	"\x0fRegisterRequest\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x1f\n" +
	"\vstart_layer\x18\x02 \x01(\x05R\n" +
	"startLayer\x12\x1b\n" +
	"\tend_layer\x18\x03 \x01(\x05R\bendLayer\"F\n" +
	"\x10RegisterResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"L\n" +
	"\fRouteRequest\x12\x1f\n" +
	"\vstart_layer\x18\x01 \x01(\x05R\n" +
	"startLayer\x12\x1b\n" +
	"\tend_layer\x18\x02 \x01(\x05R\bendLayer\"-\n" +
	"\rRouteResponse\x12\x1c\n" +
	"\taddresses\x18\x01 \x03(\tR\taddresses\"~\n" +
	"\x0eForwardRequest\x12&\n" +
	"\x06tensor\x18\x01 \x01(\v2\x0e.petals.TensorR\x06tensor\x12\x14\n" +
	"\x05route\x18\x02 \x03(\tR\x05route\x12.\n" +
	"\x13current_route_index\x18\x03 \x01(\x05R\x11currentRouteIndex\"9\n" +
	"\x0fForwardResponse\x12&\n" +
	"\x06tensor\x18\x01 \x01(\v2\x0e.petals.TensorR\x06tensor2\x8f\x01\n" +
	"\x10BootstrapService\x12A\n" +
	"\fRegisterNode\x12\x17.petals.RegisterRequest\x1a\x18.petals.RegisterResponse\x128\n" +
	"\tFindRoute\x12\x14.petals.RouteRequest\x1a\x15.petals.RouteResponse2L\n" +
	"\n" +
	"P2PService\x12>\n" +
	"\aForward\x12\x16.petals.ForwardRequest\x1a\x17.petals.ForwardResponse(\x010\x01B\rZ\vcalyx/protob\x06proto3"

var (
	file_proto_petals_proto_rawDescOnce sync.Once
	file_proto_petals_proto_rawDescData []byte
)

func file_proto_petals_proto_rawDescGZIP() []byte {
	file_proto_petals_proto_rawDescOnce.Do(func() {
		file_proto_petals_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_petals_proto_rawDesc), len(file_proto_petals_proto_rawDesc)))
	})
	return file_proto_petals_proto_rawDescData
}

var file_proto_petals_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_petals_proto_goTypes = []any{
	(*Tensor)(nil),           // 0: petals.Tensor
	(*RegisterRequest)(nil),  // 1: petals.RegisterRequest
	(*RegisterResponse)(nil), // 2: petals.RegisterResponse
	(*RouteRequest)(nil),     // 3: petals.RouteRequest
	(*RouteResponse)(nil),    // 4: petals.RouteResponse
	(*ForwardRequest)(nil),   // 5: petals.ForwardRequest
	(*ForwardResponse)(nil),  // 6: petals.ForwardResponse
}
var file_proto_petals_proto_depIdxs = []int32{
	0, // 0: petals.ForwardRequest.tensor:type_name -> petals.Tensor
	0, // 1: petals.ForwardResponse.tensor:type_name -> petals.Tensor
	1, // 2: petals.BootstrapService.RegisterNode:input_type -> petals.RegisterRequest
	3, // 3: petals.BootstrapService.FindRoute:input_type -> petals.RouteRequest
	5, // 4: petals.P2PService.Forward:input_type -> petals.ForwardRequest
	2, // 5: petals.BootstrapService.RegisterNode:output_type -> petals.RegisterResponse
	4, // 6: petals.BootstrapService.FindRoute:output_type -> petals.RouteResponse
	6, // 7: petals.P2PService.Forward:output_type -> petals.ForwardResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_petals_proto_init() }
func file_proto_petals_proto_init() {
	if File_proto_petals_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_petals_proto_rawDesc), len(file_proto_petals_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_proto_petals_proto_goTypes,
		DependencyIndexes: file_proto_petals_proto_depIdxs,
		MessageInfos:      file_proto_petals_proto_msgTypes,
	}.Build()
	File_proto_petals_proto = out.File
	file_proto_petals_proto_goTypes = nil
	file_proto_petals_proto_depIdxs = nil
}
